### ISSUE TITLE
BiocAsia2020 sticker

### ISSUE THREAD

**Issue by Liubuntu** [Bioconductor/BiocAsia2020#1]
Hi @PeteHaitch and Matt (not sure about the github id), 

I remember you have mentioned Dr. Rob Patro? for help in designing the sticker, right? Can you tag him here and can we use this issue for the sticker related communication? Thanks!

Best,
Qian

**Comment by PeteHaitch** [comment]
Hi @Liubuntu, it's Roberto Bonelli (@Robbie90) who may be able to help us with a sticker.
Robbie: Would you interested in designing a sticker for BioC Asia 2019 (in Sydney) and BioC Asia 2020 (in Tsinghua). I think we can arrange payment but just need to figure out details.

**Comment by Liubuntu** [comment]
Thanks Peter @PeteHaitch . It will be great if @Robbie90 could help with it!

**Comment by Robbie90** [comment]
Hi all, @PeteHaitch I've already designed the 2019 BiocAsia sticker and Saskia Freytag has the final model. I could take care of the 2020 one but I'm not sure on the timing for that. Do you have any deadline for this?

**Comment by PeteHaitch** [comment]
Excellent, I didn't realise Sas already had it.
Thank you!

For 2020, it'd be cool to have something mid-late November. I'm going to China in late November and would love to advertise next year's meeting - it'd be cool to have some stickers to hand out!

**Comment by Liubuntu** [comment]
:) May I provide some of my initial ideas about the BiocAsia2020 stickers? 

I think it could be great If we can make some combination of Bioconductor (the musical note) and some Chinese signature symbols, such as the Great Wall (with twists and turns to complete musical note?), the Chinese Long (red, golden), or the forbidden city. 

I'm open to bolder ideas by the professionals. @Robbie90 

Also, do you guys mind sharing the BiocAsia 2019 sticker? Or where can I see it?

**Comment by PeteHaitch** [comment]
> Also, do you guys mind sharing the BiocAsia 2019 sticker? Or where can I see it?
https://bioconductor.github.io/BiocAsia/

**Comment by PeteHaitch** [comment]
Courtesy of @Robbie90 
[BiocAsia2020.pdf](https://github.com/Bioconductor/BiocAsia2020/files/3862234/BiocAsia2020.pdf)

**Comment by Liubuntu** [comment]
Thanks @PeteHaitch ! It looks very nice, and I love the color theme! Thank you @Robbie90 for the creative work. I wonder if you can explain a little bit about the figure? I have also just shared it with our Tsinghua collaborators, and look forward to hearing back from them.
