### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BiocAsia2020#20]
- [x] Provide list of workshops here so that @PeteHaitch can include in registration form?
- [x] Update https://github.com/Bioconductor/BiocAsia2020/blob/master/docs/workshops.md with details of workshops
- [x] Provide instructions to workshop instructors (see https://github.com/Bioconductor/BioC2020/blob/master/docs/workshops.md and try to follow what was done for BioC 2020)
- [x] Coordinate cloud computing resources with @seandavi

**Comment by PeteHaitch** [comment]
@LihuaJulieZhu will co-ordinate

**Comment by seandavi** [comment]
It may be helpful to have folks adopt something like:

https://github.com/seandavi/BuildABiocWorkshop2020 / https://seandavi.github.io/BuildABiocWorkshop2020

Feel free to fork and rebrand as you see fit.

**Comment by seandavi** [comment]
You may want to include @nturaga in discussions since so much depends on the Bioc docker images.

**Comment by Liubuntu** [comment]
Hi @nturaga , would you be willing to help out here for the workshop docker image for BiocAsia? If yes, we will reach out to you once we start testing. Thank you! @mtmorgan

**Comment by nturaga** [comment]
Yes, I think I can help as needed for the image.

The best path might be to freeze a certain working version of the
`bioconductor/bioconductor_docker:devel` once you have tested against the
needs of the workshop. We can make required changes and freeze it to
`bioconductor_docker:biocasia2020`.

**Comment by nturaga** [comment]
Did this proceed in a smooth manner @Liubuntu @seandavi?

**Comment by PeteHaitch** [comment]
Sean's been an amazing help to @Liubuntu and me in getting this set up. 
All the workshops are now available from http://workshop.bioc.cancerdatasci.org/

**Comment by seandavi** [comment]
It's been straightforward for me. The docker containers are absolutely key--thanks, @nturaga. And @Liubuntu and the broader organizational team have been very actively dealing with issues.

**Comment by nturaga** [comment]
This is great to hear!

Hope the workshops go well!
