### ISSUE TITLE
The title of our workshop is not terribly applealing.

### ISSUE THREAD

**Issue by stemangiola** [Bioconductor/BiocAsia2020#31]
I'm not sure if the workshop name was changed from ours. If it's not terribly complicated it would be nice to convert it to.

tidytranscriptomics: analysing single-cell and bulk RNA sequencing data following the tidy data paradigm

**Comment by PeteHaitch** [comment]
I think the title is whatever you originally submitted.
Please make a PR to https://github.com/Bioconductor/BiocAsia2020/blob/master/docs/workshops.md if you'd like it changed there

**Comment by PeteHaitch** [comment]
But also note that this change won't affect https://biocasia2020.bioconductor.org/schedule (I don't think this is as easy to change but perhaps @Liubuntu is able to)

**Comment by stemangiola** [comment]
Thanks Pete.

> I think the title is whatever you originally submitted.

I must have been terribly tired! :)
