### ISSUE TITLE
conference web site 'live'?

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocAsia2020#4]
it would be helpful to have a live website at the link indicated in the README https://bioconductor.github.io/BiocAsia2020. The content could be basic at the moment, with tentative dates and locations. Would you like help with setting that up?

**Comment by Liubuntu** [comment]
Yes. I created a branch and have just tested locally in success. Will need to make some further edits before merging into master.

**Comment by Liubuntu** [comment]
Hi @mtmorgan , 

The webpage is alive now at: biocasia2020.bioconductor.org. 

I have created a pull request by adding contents like organizing committee, code of conduct, sponsorship oportunities and past conferences, etc. Once reviewed and merged, there will be some basic info readily available on the website. 

Best,
Qian
